name: 'PR Tracker'
description: 'Find similar or duplicated Pull Requests'

inputs:
  owner:
    description: 'Name of the owner or organization'
    default: ${{ github.repository_owner }}

  repository:
    description: 'Name of the repository'
    default: ${{ github.event.repository.name }}

  pr_number:
    description: 'Number of the Pull Request'
    default: ${{ github.event.number }}

  token:
    description: 'Token required to use GitHub CLI in a GitHub Actions workflow'
    default: ${{ github.token }}

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'mateusabelli/pr-tracker'
        ref: 'main'
    - run: '. check_pulls.sh /
            && . check_conflicts.sh /
            && . comment.sh'

      shell: bash
      env:
        OWNER: ${{ inputs.owner }}
        REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GH_TOKEN: ${{ inputs.token }}
