name: 'PR Tracker'
description: 'Find similar or duplicated Pull Requests'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

  owner:
    description: 'Name of the owner or organization'
    default: 'bootcamp-org' # CHANGE THIS

  repository:
    description: 'Name of the repository'
    default: 'actions-hero' # CHANGE THIS

  token:
    description: 'Token required to use GitHub CLI in a GitHub Actions workflow'
    default: ${{ github.token }}

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: goodbye.sh
      shell: bash
    - run: pulls.sh
      shell: bash
      env:
        OWNER: ${{ inputs.owner }}
        REPOSITORY: ${{ inputs.repository }}
        GH_TOKEN: ${{ inputs.token }}
